### ISSUE TITLE
Scroll Settings

### ISSUE THREAD

**Issue by dispeakble** [hccampos/smooth-scroll-plugin#1]
Hello!

Nice plugin you've got there! Great work!

I tested out this little plugin and it works just fine, except for a little list of issues that I've encountered:

the scroll duration is too long;
the scroll span is too wide/much;
the scroll animation doesn't stop if you scroll in the other direction while animating;
the scroll doesn't start sometimes, if you scroll only one _click_;
I'd like to set my scroll speed accordingly to my monitor refresh rate for a simulation of v-sync (eg: 2 px \* framerate = 120px / sec) -- additionaly I'd like to control the sliding effect (the easing) because it takes too much to stop;
how about horizontal scrolling (shift + scroll)?;
As you can see, there is a stuttering effect due to lack of v-sync; can this be fixed?
Some futuristic fetures I'd like to see:
- motion blur :)
- easing in and out or controlling the easing like in jquery

check out the settings for this chrome extension: Chromium Wheel Smooth Scroller -- I think that it will inspire you to perfect this plugin for everyone's needs;
I can help you with this project if you like;

Contact me if you have the time and / or interest to improve the UI experience for the jetbrains editors;

Cheers!

**Comment by samupl** [comment]
I think scroll settings would be a good feature, I don't really like the default settings. It would be nice to configure the plugin to fit my needs ;)

**Comment by Pepetruen0** [comment]
I also think that while the functionality is great, the default settings are less than optimal. A settings inteface would be a great addition.

**Comment by hccampos** [comment]
Yes, indeed, I remember that at the time I configured it for my laptop or something like that. In any case, I haven't used IntelliJ IDEA or WebStorm in almost a year, nor have I touched Java in that time period. So if anyone wishes to submit a PR, that would be awesome.

**Comment by bofm** [comment]
Can anyone suggest a variable to adjust to get a slightly faster animation?

**Comment by markhicken** [comment]
I wish it worked well with the built-in scroll acceleration on Mac. :(
